spring:
  application:
    name: jainam-billing-system
  datasource:
    url: jdbc:mysql://pyho-0.h.filess.io:61001/jainam_billing_placemanat?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: jainam_billing_placemanat
    password: f6eaec84942d07d9d9f45c9613a89fb48a7f62d5
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: piyushiaf5445@gmail.com
    password: btmx ccio ktrv pvde
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    root: INFO
    com.jainam: DEBUG
