import React, { useState, useEffect } from "react";
import { clientAPI } from "../services/api";
import { Plus, Edit2, Trash2, Search, Copy, Check, KeyRound, Eye, EyeOff } from "lucide-react";
export default function Clients() {
  const [clients, setClients] = useState([]);
  const [loading, setLoading] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState(false);
  const [editingId, setEditingId] = useState("");
  const [formData, setFormData] = useState({
    company: "",
    contactPerson: "",
    phone: "",
    email: "",
    gstNumber: "",
    address: "",
    password: "",
  });

  // Storefront login credentials, surfaced right after a client is created
  // so they can be shared. The password is also now visible/editable later
  // from the table below and the edit form.
  const [newCredentials, setNewCredentials] = useState(null);
  const [copied, setCopied] = useState("");
  const [showFormPassword, setShowFormPassword] = useState(false);
  const [visiblePasswordIds, setVisiblePasswordIds] = useState(new Set());

  const togglePasswordVisible = (id) => {
    setVisiblePasswordIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  useEffect(() => {
    loadClients();
  }, []);

  const loadClients = async () => {
    try {
      setLoading(true);
      const response = await clientAPI.getAll();
      setClients(response.data || []);
    } catch (err) {
      console.error(err);
      alert("Failed to load clients");
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      if (editing) {
        await clientAPI.update(editingId, formData);
      } else {
        const res = await clientAPI.create(formData);
        // Storefront login credentials are auto-generated by the backend
        // and returned exactly once — surface them now so they can be
        // shared with the client.
        if (res?.data?.username) {
          setNewCredentials({
            company: formData.company,
            username: res.data.username,
            password: res.data.password,
          });
        }
      }

      setFormData({
        company: "",
        contactPerson: "",
        phone: "",
        email: "",
        gstNumber: "",
        address: "",
        password: "",
      });

      setEditing(false);
      setEditingId(null);
      setShowForm(false);

      loadClients();
    } catch (error) {
      console.error(error);
      alert("Operation failed");
    }
  };
  const handleEdit = (client) => {
    setEditing(true);
    setEditingId(client.id);

    setFormData({
      company: client.company,
      contactPerson: client.contactPerson,
      phone: client.phone,
      email: client.email,
      gstNumber: client.gstNumber,
      address: client.address,
      password: client.password || "",
    });

    setShowForm(true);
  };

  const handleDelete = async (id) => {
    if (!window.confirm("Are you sure you want to deactivate this client?")) {
      return;
    }

    try {
      await clientAPI.delete(id);
      loadClients();
    } catch (error) {
      console.error(error);
      alert("Failed to deactivate client");
    }
  };

  const handleCopy = async (text, label) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(label);
      setTimeout(() => setCopied(""), 1500);
    } catch {
      // clipboard API unavailable — silently ignore, text is still visible
    }
  };

  const filteredClients = clients.filter(
    (client) =>
      client.company?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      client.contactPerson?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      client.email?.toLowerCase().includes(searchTerm.toLowerCase()),
  );

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-800">Clients</h1>
          <p className="text-gray-500 text-sm sm:text-base">Manage your clients</p>
        </div>

        <button
          onClick={() => setShowForm(true)}
          className="btn-primary flex items-center justify-center gap-2 w-full sm:w-auto"
        >
          <Plus size={20} />
          Add Client
        </button>
      </div>

      {newCredentials && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center px-4">
          <div className="bg-white rounded-lg shadow-xl p-6 w-full max-w-sm">
            <div className="flex items-center gap-2 text-primary mb-1">
              <KeyRound size={20} />
              <h2 className="text-lg font-bold">Storefront login created</h2>
            </div>
            <p className="text-sm text-gray-500 mb-4">
              Share these with <span className="font-medium">{newCredentials.company}</span> so
              they can log in and place orders. You can view or change this password anytime from the clients table.
            </p>

            <div className="space-y-3">
              <div className="flex items-center justify-between bg-gray-50 border rounded-lg px-3 py-2">
                <div>
                  <div className="text-xs text-gray-400">Username</div>
                  <div className="font-mono text-sm">{newCredentials.username}</div>
                </div>
                <button
                  onClick={() => handleCopy(newCredentials.username, "username")}
                  className="text-gray-500 hover:text-primary"
                >
                  {copied === "username" ? <Check size={18} className="text-green-600" /> : <Copy size={18} />}
                </button>
              </div>

              <div className="flex items-center justify-between bg-gray-50 border rounded-lg px-3 py-2">
                <div>
                  <div className="text-xs text-gray-400">Password</div>
                  <div className="font-mono text-sm">{newCredentials.password}</div>
                </div>
                <button
                  onClick={() => handleCopy(newCredentials.password, "password")}
                  className="text-gray-500 hover:text-primary"
                >
                  {copied === "password" ? <Check size={18} className="text-green-600" /> : <Copy size={18} />}
                </button>
              </div>
            </div>

            <button
              onClick={() => setNewCredentials(null)}
              className="btn-primary w-full mt-5"
            >
              Done
            </button>
          </div>
        </div>
      )}

      {showForm && (
        <form
          onSubmit={handleSubmit}
          className="bg-white rounded-lg shadow p-4 sm:p-6 space-y-4"
        >
          <input
            className="w-full border p-2 rounded"
            name="company"
            placeholder="Company"
            value={formData.company}
            onChange={handleChange}
            required
          />

          <input
            className="w-full border p-2 rounded"
            name="contactPerson"
            placeholder="Contact Person"
            value={formData.contactPerson}
            onChange={handleChange}
            required
          />

          <input
            className="w-full border p-2 rounded"
            name="phone"
            placeholder="Phone"
            value={formData.phone}
            onChange={handleChange}
          />

          <input
            className="w-full border p-2 rounded"
            name="email"
            placeholder="Email"
            value={formData.email}
            onChange={handleChange}
          />

          <input
            className="w-full border p-2 rounded"
            name="gstNumber"
            placeholder="GST Number"
            value={formData.gstNumber}
            onChange={handleChange}
          />

          <textarea
            className="w-full border p-2 rounded"
            name="address"
            placeholder="Address"
            value={formData.address}
            onChange={handleChange}
          />

          <div className="relative">
            <input
              className="w-full border p-2 rounded pr-10"
              name="password"
              type={showFormPassword ? "text" : "password"}
              placeholder={editing ? "Storefront password" : "Storefront password (leave blank to auto-generate)"}
              value={formData.password}
              onChange={handleChange}
              autoComplete="new-password"
            />
            <button
              type="button"
              onClick={() => setShowFormPassword((v) => !v)}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
              tabIndex={-1}
            >
              {showFormPassword ? <EyeOff size={18} /> : <Eye size={18} />}
            </button>
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <button
              type="submit"
              className="bg-green-600 text-white px-4 py-2 rounded w-full sm:w-auto"
            >
              {editing ? "Update" : "Save"}
            </button>

            <button
              type="button"
              onClick={() => setShowForm(false)}
              className="bg-gray-500 text-white px-4 py-2 rounded w-full sm:w-auto"
            >
              Cancel
            </button>
          </div>
        </form>
      )}

      <div className="bg-white rounded-lg shadow p-4">
        <div className="flex items-center gap-2">
          <Search size={20} className="text-gray-400 shrink-0" />

          <input
            type="text"
            placeholder="Search clients..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="flex-1 px-3 py-2 border rounded min-w-0"
          />
        </div>
      </div>

      <div className="bg-white rounded-lg shadow overflow-hidden">
        {loading ? (
          <div className="p-6 text-center">Loading...</div>
        ) : filteredClients.length === 0 ? (
          <div className="p-6 text-center">No clients found</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px]">
              <thead className="bg-gray-100">
                <tr>
                  <th className="p-3 text-left">Company</th>
                  <th className="p-3 text-left">Contact</th>
                  <th className="p-3 text-left">Email</th>
                  <th className="p-3 text-left">Phone</th>
                  <th className="p-3 text-left">GST</th>
                  <th className="p-3 text-left">Login</th>
                  <th className="p-3 text-left">Password</th>
                  <th className="p-3 text-left">Status</th>
                  <th className="p-3 text-center">Action</th>
                </tr>
              </thead>

              <tbody>
                {filteredClients.map((client) => (
                  <tr key={client.id} className="border-b">
                    <td className="p-3">{client.company}</td>
                    <td className="p-3">{client.contactPerson}</td>
                    <td className="p-3">{client.email}</td>
                    <td className="p-3">{client.phone}</td>
                    <td className="p-3">{client.gstNumber}</td>
                    <td className="p-3 font-mono text-xs text-gray-600">
                      {client.username || "—"}
                    </td>
                    <td className="p-3">
                      {client.password ? (
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-xs text-gray-600">
                            {visiblePasswordIds.has(client.id)
                              ? client.password
                              : "•".repeat(Math.max(client.password.length, 6))}
                          </span>
                          <button
                            onClick={() => togglePasswordVisible(client.id)}
                            className="text-gray-400 hover:text-gray-600"
                            title={visiblePasswordIds.has(client.id) ? "Hide password" : "Show password"}
                          >
                            {visiblePasswordIds.has(client.id) ? <EyeOff size={16} /> : <Eye size={16} />}
                          </button>
                        </div>
                      ) : (
                        "—"
                      )}
                    </td>
                    <td className="p-3">
                      {client.active ? (
                        <span className="text-green-600 font-semibold">
                          Active
                        </span>
                      ) : (
                        <span className="text-red-600 font-semibold">
                          Inactive
                        </span>
                      )}
                    </td>
                    <td className="p-3 text-center">
                      <button
                        onClick={() => handleEdit(client)}
                        className="text-blue-600 hover:text-blue-800"
                      >
                        <Edit2 size={18} />
                      </button>
                      <button
                        onClick={() => {
                          console.log("Clicked delete", client.id);
                          handleDelete(client.id);
                        }}
                        className="text-red-600 hover:text-red-800 ml-2"
                      >
                        <Trash2 size={18} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
